language: node_js  
node_js:
  - "node"

install:
  - npm build

script: echo "npm test temporarily disabled" 

addons:
  artifacts:
    target_paths:
     - /com.shareholdergame/ui/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
    debug: true 
