language: node_js  
node_js:
  - "node"

script:
  - npm run build 

addons:
  artifacts:
    paths: 
     - build
    target_paths:
     - /com.shareholdergame/ui/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
    debug: true 

notifications:
  email:
    - admin@stockholdergame.com    
